### ISSUE TITLE
Error while creating new user

### ISSUE THREAD

**Issue by kar0n** [usrbinsam/mini-key-server#8]
Hey there,
While creating a new user with flask I am facing this error   - 

(venv) C:\Users\admin\Desktop\mini-key-server-master>flask create-user username password
Traceback (most recent call last):
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\util\compat.py", line 154, in reraise
    raise value
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\engine\default.py", line 451, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\admin\Anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\Desktop\mini-key-server-master\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\flask\cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\flask\cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\admin\Desktop\mini-key-server-master\keyserv\__init__.py", line 71, in create_user_command
    add_user(username, password.encode())
  File "C:\Users\admin\Desktop\mini-key-server-master\keyserv\auth.py", line 37, in add_user
    db.session.commit()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1027, in commit
    self.transaction.commit()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 494, in commit
    self._prepare_impl()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 473, in _prepare_impl
    self.session.flush()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2459, in flush
    self._flush(objects)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\util\compat.py", line 154, in reraise
    raise value
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2557, in _flush
    flush_context.execute()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 213, in save_obj
    ) in _organize_states_for_save(base_mapper, states, uowtransaction):
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 374, in _organize_states_for_save
    base_mapper, uowtransaction, states
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 1605, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 313, in connection
    return self._connection_for_bind(bind, execution_options)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 419, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind, execution_options)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 431, in _connection_for_bind
    conn = bind._contextual_connect()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2226, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2266, in _wrap_pool_connect
    e, dialect, self
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1536, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\util\compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\util\compat.py", line 154, in reraise
    raise value
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\pool\base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\sqlalchemy\engine\default.py", line 451, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "c:\users\admin\desktop\mini-key-server-master\venv\lib\site-packages\psycopg2\__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied

(Background on this error at: http://sqlalche.me/e/e3q8)

How do I fix this?

**Comment by krs92** [comment]
How i fixed was, 
Either give proper endpoint in config.py with database endpoint or create a user keyserver

**Comment by usrbinsam** [comment]
Are you still having an issue with this?

**Comment by kar0n** [comment]
No, it's resolved. Thank You.

**Comment by jeann3** [comment]
Hello, I'm having the same issue and creating a user "keyserver" and trying several URIs doesn't solve it, could you help me?
To create a user I've tried "flask create-user username password" and "flask create-user keyserver password"
In the config.py I've tried SQLALCHEMY_DATABASE_URI = "postgres://localhost/keyserver", SQLALCHEMY_DATABASE_URI = "postgres://keyserver@localhost", SQLALCHEMY_DATABASE_URI = "postgres://username:password@localhost"
